# Check if e2e-desktop should run: trigger in comment, or (optional) main branch, or [e2e] in commit.
# Use in e2e-desktop-comment.yml (comment only) or ci.yml (comment + main + commit).

name: Check comment trigger
description: Check if trigger phrase in PR comment; optionally also main branch or [e2e] in commit
inputs:
  trigger:
    description: Trigger phrase to look for (e.g. /e2e-desktop)
    required: true
  check_main:
    description: Also return true when ref is refs/heads/main
    required: false
    default: "false"
  check_commit:
    description: Also return true when [e2e] in commit message
    required: false
    default: "false"
  allow_workflow_dispatch:
    description: When true, workflow_dispatch events always return true (for manual runs)
    required: false
    default: "false"
outputs:
  should_run:
    description: "true if any condition matches, else false"
    value: ${{ steps.check.outputs.should_run }}
runs:
  using: composite
  steps:
    - name: Check if e2e-desktop should run
      id: check
      uses: actions/github-script@v7
      env:
        TRIGGER: ${{ inputs.trigger }}
        CHECK_MAIN: ${{ inputs.check_main }}
        CHECK_COMMIT: ${{ inputs.check_commit }}
        ALLOW_WORKFLOW_DISPATCH: ${{ inputs.allow_workflow_dispatch }}
      with:
        script: |
          const trigger = process.env.TRIGGER;
          const checkMain = process.env.CHECK_MAIN === 'true';
          const checkCommit = process.env.CHECK_COMMIT === 'true';
          const allowWorkflowDispatch = process.env.ALLOW_WORKFLOW_DISPATCH === 'true';

          if (allowWorkflowDispatch && context.eventName === 'workflow_dispatch') {
            core.setOutput('should_run', 'true');
            return;
          }

          if (checkMain && context.ref === 'refs/heads/main') {
            core.setOutput('should_run', 'true');
            return;
          }

          if (checkCommit) {
            let msg = '';
            if (context.eventName === 'push' && context.payload.head_commit) {
              msg = context.payload.head_commit.message || '';
            } else if (context.eventName === 'pull_request' && context.payload.pull_request) {
              const pr = context.payload.pull_request;
              const { data: commit } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pr.head.sha,
              });
              msg = commit.commit?.message || '';
            }
            if (msg.includes('[e2e]')) {
              core.setOutput('should_run', 'true');
              return;
            }
          }

          let commentMatch = false;
          if (context.eventName === 'issue_comment' && context.payload.issue?.pull_request) {
            commentMatch = (context.payload.comment?.body || '').includes(trigger);
          } else if (context.eventName === 'pull_request' && context.payload.pull_request) {
            const pr = context.payload.pull_request;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
            });
            commentMatch = comments.some(c => c.body && c.body.includes(trigger));
          }

          core.setOutput('should_run', commentMatch ? 'true' : 'false');
