name: Install Linux deps
description: Install build and runtime deps for Tauri app on Ubuntu
inputs:
  e2e:
    description: Include E2E desktop deps (webkit2gtk-driver, xvfb, gnome-keyring)
    required: false
    default: 'false'
  verify_glib:
    description: Run glib verification (dpkg, pkg-config checks)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Install Linux deps
      shell: bash
      run: |
        BASE_DEPS="build-essential pkg-config libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libsecret-1-dev"
        E2E_DEPS="webkit2gtk-driver xvfb gnome-keyring"
        sudo apt-get update
        if [ "${{ inputs.e2e }}" = "true" ]; then
          sudo apt-get install -y $BASE_DEPS $E2E_DEPS
        else
          sudo apt-get install -y $BASE_DEPS
        fi
        if [ "${{ inputs.verify_glib }}" = "true" ]; then
          echo "=== Verifying glib-2.0 installation ==="
          dpkg -l | grep libglib2.0-dev || echo "libglib2.0-dev not installed"
          find /usr -name 'glib-2.0.pc' 2>/dev/null || echo "glib-2.0.pc not found"
          pkg-config --modversion glib-2.0 || echo "pkg-config cannot find glib-2.0"
          pkg-config --exists 'glib-2.0 >= 2.70' && echo "glib-2.0 >= 2.70 found" || (echo "ERROR: glib-2.0 >= 2.70 not found"; exit 1)
        fi
        echo "PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config)" >> $GITHUB_ENV
